#!/usr/bin/env bash
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -xeuo pipefail

echo "Gate job started"
echo "+-------------------- START ENV VARS --------------------+"
env
echo "+-------------------- END ENV VARS --------------------+"

export RE_JOB_SCENARIO=${RE_JOB_SCENARIO:-"functional"}
export RPC_MAAS_DIR=${RPC_MAAS_DIR:-/opt/rpc-maas}
export TEST_RPC_MAAS=${TEST_RPC_MAAS:-True}

# Install python2 and python3-virtualenv for Ubuntu 16.04
if which apt-get; then
    sudo apt-get update && sudo apt-get install -y python python3-virtualenv
fi

# Install pip.
if ! which pip; then
  curl --silent --show-error --retry 5 \
    https://bootstrap.pypa.io/get-pip.py | sudo python2.7
fi

# Install bindep and tox with pip.
sudo pip install bindep tox

virtualenv --python python3 .rpc_component_venv

.rpc_component_venv/bin/pip install "git+https://github.com/rcbops/rpc_component@85f152ece9eee3c9cd7d68bd2ecc5982e17400ae#egg=rpc_component"
.rpc_component_venv/bin/component dependency download-requirements --download-dir /opt

if [ "${RE_JOB_SCENARIO}" = "functional" ]; then
  export CLONE_DIR="$(pwd)"
  export ANSIBLE_INVENTORY="${CLONE_DIR}/tests/inventory"
  export ANSIBLE_OVERRIDES="${CLONE_DIR}/tests/test-vars.yml"
  export ANSIBLE_BINARY="${ANSIBLE_BINARY:-/opt/rpc-hummingbird-ansible-runtime/bin/ansible-playbook}"
  bash scripts/bootstrap-ansible.sh
  bash scripts/set-static-rings.sh
  # Clone the test repos
  pushd playbooks
    ${ANSIBLE_BINARY} git-clone-repos.yml \
    	-i ${CLONE_DIR}/tests/inventory \
        -e role_file=../ansible-role-test-requirements.yml
    ln -s /etc/ansible/roles/rpc-maas/tests/common /opt/rpc-maas/tests/common
  popd

  ${ANSIBLE_BINARY} -i tests/inventory tests/setup-hummingbird-test.yml -e @tests/test-vars.yml
  # Use the rpc-maas deploy to test MaaS
  if [ "${TEST_RPC_MAAS}" != "False" ]; then
    pushd ${RPC_MAAS_DIR}
      export RE_JOB_SCENARIO="hummingbird"
      ## This is needed for the maas job to be able to update the apt cache
      ## When the influxdb repo is present.
      apt-get install -y apt-transport-https
      bash tests/test-ansible-functional.sh
    popd
  fi
else
  echo "Implement tox bits if necessary"
fi
