---
- hosts: hummingbird-admin
  user: root
  tasks:
    - name: setup openrc
      template:
        src: templates/openrc.j2
        dest: /root/openrc
        mode: 600

- name: Install Hummingbird Keystone config
  hosts: localhost
  user: root
  pre_tasks:
    - name: Install python-keystoneclient
      pip:
        name: python-keystoneclient
        state: present
        extra_args: "--ignore-installed"
      delegate_to: 127.0.0.1
      run_once: true
      when: hbird_keystone | bool
      register: install_pkgs
      until: install_pkgs|success
      retries: 5
      delay: 2
    - name: Ensure hbird service
      keystone:
        command: "ensure_service"
        endpoint: "{{ auth_url }}/v3"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        service_name: "{{ hbird_keystone_service_name }}"
        service_type: "{{ hbird_keystone_service_type }}"
        description: "{{ hbird_keystone_service_description }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      delegate_to: 127.0.0.1
      run_once: true
      when: hbird_keystone | bool
      register: add_service
      until: add_service|success
      retries: 5
      delay: 2
      #no_log: True
    - name: Ensure hbird user
      keystone:
        command: "ensure_user"
        endpoint: "{{ auth_url }}/v3"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        user_name: "{{ authtoken_username }}"
        tenant_name: "{{ hbird_keystone_admin_tenant }}"
        role_name: "{{ hbird_keystone_role_name | default('service') }}"
        password: "{{ authtoken_password }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      delegate_to: 127.0.0.1
      run_once: true
      when: hbird_keystone | bool
      register: add_service
      until: add_service|success
      retries: 5
      delay: 10
      #no_log: True
    - name: Ensure hbird user to admin role
      keystone:
        command: "ensure_user_role"
        endpoint: "{{ auth_url }}/v3"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        user_name: "{{ authtoken_username }}"
        tenant_name: "{{ hbird_keystone_admin_tenant }}"
        role_name: "{{ hbird_keystone_role_name | default('admin') }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      delegate_to: 127.0.0.1
      run_once: true
      register: add_admin_role
      when: hbird_keystone | bool
      until: add_admin_role|success
      retries: 5
      delay: 10
      #no_log: True
    - name: Ensure hbird endpoint
      keystone:
        command: "ensure_endpoint"
        endpoint: "{{ auth_url }}/v3"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        region_name: "{{ service_region }}"
        service_name: "{{ hbird_keystone_service_name }}"
        service_type: "{{ hbird_keystone_service_type }}"
        insecure: "{{ keystone_service_adminuri_insecure }}"
        endpoint_list:
          - url: "{{ hbird_service_publicurl }}"
            interface: "public"
          - url: "{{ hbird_service_adminurl }}"
            interface: "admin"
          - url: "{{ hbird_service_internalurl }}"
            interface: "internal"
      delegate_to: 127.0.0.1
      run_once: true
      register: add_service
      when: hbird_keystone | bool
      until: add_service|success
      retries: 5
      delay: 10
      #no_log: True
