---
- name: Install Hummingbird Keystone config
  hosts: localhost
  user: root
  pre_tasks:
    - name: Install python-keystoneclient
      pip:
        name: python-keystoneclient
        state: present
        extra_args: "--ignore-installed"
      delegate_to: 127.0.0.1
      run_once: true
      when: hbird_keystone | bool
      register: install_pkgs
      until: install_pkgs|success
      retries: 5
      delay: 2
    - name: Ensure swiftoperator role
      keystone:
        command: "ensure_role"
        endpoint: "{{ auth_url }}/v3"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        role_name: "swiftoperator"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      delegate_to: 127.0.0.1
      run_once: true
      when: hbird_keystone | bool
      register: add_role
      until: add_role|success
      retries: 5
      delay: 5
      #no_log: True
    - name: Ensure test project
      keystone:
        command: "ensure_project"
        endpoint: "{{ auth_url }}/v3"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        project_name: "test"
        description: "test project"
        domain_name: "Default"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      delegate_to: 127.0.0.1
      run_once: true
      when: hbird_keystone | bool
      register: add_project
      until: add_project|success
      retries: 5
      delay: 5 
      #no_log: True
    - name: Ensure test user
      keystone:
        command: "ensure_user"
        endpoint: "{{ auth_url }}/v3"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        user_name: "tester"
        project_name: "test"
        password: "testing"
        domain_name: "Default"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      delegate_to: 127.0.0.1
      run_once: true
      register: add_role
      when: hbird_keystone | bool
      until: add_role|success
      retries: 5
      delay: 5
      #no_log: True
    - name: Ensure test user to swiftoperator role
      keystone:
        command: "ensure_user_role"
        endpoint: "{{ auth_url }}/v3"
        login_user: "{{ keystone_admin_user_name }}"
        login_password: "{{ keystone_auth_admin_password }}"
        login_project_name: "{{ keystone_admin_tenant_name }}"
        user_name: "tester"
        tenant_name: "test"
        role_name: "swiftoperator"
        insecure: "{{ keystone_service_adminuri_insecure }}"
      delegate_to: 127.0.0.1
      run_once: true
      register: add_role
      when: hbird_keystone | bool
      until: add_role|success
      retries: 5
      delay: 5
      #no_log: True
